#!/bin/bash
#!

## script to look up variants in a specific region
# Submit jobs
# while IFS= read -r line; do sbatch scripts/02_reciprocal_look_up $line; done < input/


#!#############################################################
#!#### Modify the options in this section as appropriate ######
#!#############################################################

#! Name of the job:
#SBATCH -J reciprocal-look-up-pQTLs

#! Which project should be charged:
#SBATCH -A MRC-EPID-SL0-CPU

#! How many whole nodes should be allocated?
# In your case you should leave this at 1
#SBATCH --nodes=1

#SBATCH --ntasks=1

#SBATCH --cpus-per-task 3

## restrict the number of nodes to be used (maximum of 30)
#SBATCH --exclude=cpu-d-[25-30]

#! Specify required run time
#SBATCH --time=100:00:00

#! What types of email messages do you wish to receive?
#SBATCH --mail-type=FAIL

#! Uncomment this to prevent the job from being requeued (e.g. if
#! interrupted by node failure or system downtime):
##SBATCH --no-requeue

#! Do not change:
#SBATCH -p epid

#! ############################################################
#! Modify the settings below to specify the application's environment, location 
#! and launch method:

#! Optionally modify the environment seen by the application
#! (note that SLURM reproduces the environment at submission irrespective of ~/.bashrc):
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-peta4            # REQUIRED - loads the basic environment

#! Insert additional module load commands after this line if needed:

module load gcc/5

## export variables
export SL=${1}
export OL=${2}
export SNP=${3}
export SFILE=~/rds/rds-rjh234-mrc-epid/Studies/People/Ellie/SomaLogic/GWAS_discovery_subsets/Meta-Analysis/Fenland_auto_chrX_filtered/output
export OFILE=/home/mdp50/rds/rds-rjh234-mrc-epid/Studies/People/Ellie/Olink/GWAS/output/formatted/combined

echo "Do reciprocal look-up for ${SL} and ${OL} for ${SNP}"

## set the directory
cd /home/mdp50/rds/rds-rjh234-mrc-epid/Studies/People/Maik/compare_SomaLogic_Olink/01_pQTLs_Fenland

## look up SNP in SOMAscan data
zcat ${SFILE}/${SL}_Fenland_MA_auto_chrX_filtered.txt.gz | grep -w ${SNP} > output/${SL}.${SNP}.lookup

## look up SNP in Olink data 
zcat ${OFILE}/${OL}_withMarkerName.out.gz | grep -w ${SNP} > output/${OL}.$SNP.lookup
